### ISSUE TITLE
Issue Fetching ICLOUD_Family.ics

### ISSUE THREAD

**Issue by jal201** [MMRIZE/MMM-CalDAV#12]
I apologize but I am very very new to all of this and I was looking for a little guidance on syncing with my Apple Calendar using MMM-CalDAV. The issue I am running into is that in the [LOG] it is showing [CALDAV] /MagicMirror/modules/MMM-CalDAV/service/.ICLOUD_family.ics is not found. This is cascading into a lot of issues which results in the fetch of the family calendar isn't happening. I am sure I am missing something simple but I can't for the life of me find it out. Would it be possible to get some help and which direction could I investigate? Thank you all in advance.

**Comment by eouia** [comment]
<img width="920" alt="image" src="https://github.com/user-attachments/assets/fd768409-f494-4e50-9fbe-73351e87f7e1">
Maybe this issue? Could you show me the full log?

**Comment by jal201** [comment]
I have waited and tried multiple times but that doesn't seem to be the issue. I fear that it is something really small that I am missing. Please see the Log file
<img width="1180" alt="image" src="https://github.com/user-attachments/assets/03ff183a-6857-40a0-a68f-41ff0a404bcf">

**Comment by eouia** [comment]
The error message says you failed to login CalDAV Server (apple icloud?). Maybe there would be fails in your `.env` file. (Username or password for iCloud)

**Comment by jal201** [comment]
Thank you for your help and I noticed that as well. So I went in and corrected the login issue but this is now showing. Thank you again for your time and help!
<img width="1069" alt="image" src="https://github.com/user-attachments/assets/fc019c78-c1f5-4111-85ff-53fcfdaeb590">
Could this be a permission issue? Does the program need write access and how could I provide that?
Is there a preferred location to store MagicMirror? Should I move it from the directory it is in to another?

**Comment by jal201** [comment]
I seem to have the fetching issue solved by moving the base directory but I am experiencing a new issue. This new issue appears to be that the CalendarExt3 module is not loading. and the only error I am seeing in the log is:
<img width="958" alt="image" src="https://github.com/user-attachments/assets/7dd937fe-3994-4d45-9787-1b4ddfc4e809">
Any ideas on how to correct this issue? I know this probably isn't the same issue any longer but any help would be greatly appreciated.

**Comment by eouia** [comment]
Sorry for the late reply. I was on vacation.
You still have this issue?
I think `Moment timezone error` is not the reason. (It may be related to the default calendar module.)
Could you send me the example of `.ics` created by this module(`.ICLOUD_Family.ics`)
